language: objective-c
sudo: false

env:
  global:
    - PATH=$HOME/.crenv/bin:$PATH
  matrix:
    - CRYSTAL_VERSION=0.9.0
    - CRYSTAL_VERSION=0.9.1

install:
  - curl -L https://raw.github.com/pine613/crenv/master/install.sh | bash
  - eval "$(crenv init -)"
  - crenv install $CRYSTAL_VERSION
  - crenv global $CRYSTAL_VERSION
  - crystal --version

before_script:
  - make install

script:
  - make build
  - make test
  - make release

notifications:
  slack:
    - secure: "C2HvRgtDFafLaeAbUt/iQiUy7s5FUiDQTIlO2h/39cuM4lKFRnlWZO4vUNLNKIjY27XVFyLJTRk9VOiVaJziIne5gV/l7DoGfQS5mJTsLKrEyFFZ1+Kln4Jvyjfk3dKohkKAya2Fa5VP3VH1cim4nuiurctTzY7pG2v0C+Ts4ZrhN6ptO8Av5bWpt7/1yuzdNfXPnwQo0lquZKKgKNaWiuPo4MEf1Sk1nd+9US1sCDhJ+mpscCX5qvvwWAOKIjcuQXin2KaCs9q7HPFkQuS+7yNgnFao2gGOcjnnKY/WHpa4kYx4wP7wI7hIq5oxWaHZRzN372X6KGXSJnIqEKpcdQn/7S5QtdAsx4fkkFBd3Smvd7PvisDKNiGDDZ2dYdshL4fOwtgOeqBg8/ArhjhjhJ7tTl/Q3QWvqmJ1t0w1jIvCKoGDN6RQB7qhhL7hTx2yLnyB1jEDz92cmNulRItH8FSowI0izDqUYc1jNFpuLj4A9DE1g/FMo6azQZQuusiWHwhZXeY8y4Gr9bdPkeQOXAnP99m3ekQmjSRD/3MHOXSErlYFe0jVJ4KyrmNEPVRuqW28cKg8HAT+rGHbBq4XIBpl4A53DcFxGv75XZCZoS0Lhc1N+Qu+iXKL+hctOOGUUJdsuQdzv7fTdcSOSYf9xCUgzn74MpCSoOSHqwCm4lE="
